### ISSUE TITLE
Build out stats page

### ISSUE THREAD

**Issue by usern3** [KongSwap/kong#30]
## TODO
- [ ] Scaffold the various UI components to form the stats page
- [ ] Add necessary endpoints to backendService
- [ ] Implement stats table
- [ ] Implement stats sign (bottom left)
