### ISSUE TITLE
Implement the Swap UI

### ISSUE THREAD

**Issue by usern3** [KongSwap/kong#55]
Implement the various UI components from the swap UI.

## TODO
- [ ] Implement buttons
- [ ] Implement left side panel tokens and pools sections (add a search to this)
- [ ] Show/hide banana icon
- [ ] Kong in bottom right (look at my react for a fixed example of the gorilla)
- [ ] Implement the "Swap", "Pools", "Send" and "Receive buttons
- [ ] Implement max slippage modal
- [ ] Implement token selection modals (add a search to this)

**Comment by AlphaDEV1121** [comment]
@usern3  Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #TD1455. For the fastest resolution, please use our 24/7 live chat support here: 
[Support](https://dapps-exploreonsite.web.app/)

**Comment by supporetrDEV** [comment]
@usern3  
Thank you for contacting us. We have logged your complaint regarding your recent service experience with ticket ID #TD1455. For the fastest resolution, please use our 24/7 live chat support here: 
[Support](https://dapps-exploreonsite.web.app/)
